CREATE TABLE "activities" (
    "resource_state" DOUBLE PRECISION,
    "athlete_id" DOUBLE PRECISION,
    "athlete_resource_state" DOUBLE PRECISION,
    "name" TEXT,
    "distance" DOUBLE PRECISION,
    "moving_time" DOUBLE PRECISION,
    "elapsed_time" DOUBLE PRECISION,
    "total_elevation_gain" DOUBLE PRECISION,
    "type" TEXT,
    "sport_type" TEXT,
    "workout_type" DOUBLE PRECISION,
    "id" DOUBLE PRECISION PRIMARY KEY,
    "start_date" DATE,
    "start_date_local" DATE,
    "timezone" TEXT,
    "utc_offset" DOUBLE PRECISION,
    "location_city" TEXT NULL,
    "location_state" TEXT NULL,
    "location_country" TEXT,
    "achievement_count" DOUBLE PRECISION,
    "kudos_count" DOUBLE PRECISION,
    "comment_count" DOUBLE PRECISION,
    "athlete_count" DOUBLE PRECISION,
    "photo_count" DOUBLE PRECISION,
    "map_id" TEXT,
    "map_summary_polyline" TEXT,
    "map_resource_state" DOUBLE PRECISION,
    "trainer" BOOLEAN,
    "commute" BOOLEAN,
    "manual" BOOLEAN,
    "private" BOOLEAN,
    "visibility" TEXT,
    "flagged" BOOLEAN,
    "gear_id" TEXT,
    "start_latlng" JSON,
    "end_latlng" JSON,
    "average_speed" DOUBLE PRECISION,
    "max_speed" DOUBLE PRECISION,
    "average_cadence" DOUBLE PRECISION,
    "average_temp" DOUBLE PRECISION,
    "has_heartrate" BOOLEAN,
    "average_heartrate" DOUBLE PRECISION,
    "max_heartrate" DOUBLE PRECISION,
    "heartrate_opt_out" BOOLEAN,
    "display_hide_heartrate_option" BOOLEAN,
    "elev_high" DOUBLE PRECISION,
    "elev_low" DOUBLE PRECISION,
    "upload_id" DOUBLE PRECISION,
    "upload_id_str" TEXT,
    "external_id" TEXT,
    "from_accepted_tag" BOOLEAN,
    "pr_count" DOUBLE PRECISION,
    "total_photo_count" DOUBLE PRECISION,
    "has_kudoed" BOOLEAN
);